# Generated by Django 4.2.13 on 2024-07-29 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='product_cover',
            new_name='company_photo',
        ),
    ]
